--types
Bean = "bean"
String = "string"
Number = "number"
Function = "function"
Boolean = "boolean"
Table = "table"
Any = "any"
Nil = "nil"
--class element types
Method = "method"
Var = "var"
Interface = "interface"
EnumType = "enum"
Inner = "inner"
--modifiers
Static = "static"
Final = "final"
Abstract = "abstract"
--access modifiers
Package = "package"
Private = "private"
Protected = "protected"
Public = "public"
Getter = "getter"
Setter = "setter"
